// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-61HEKmPgGEHFRN688hb3B-vAKiFXgBA',
    appId: '1:447433637466:web:9e2fbf81c36aee5aba6263',
    messagingSenderId: '447433637466',
    projectId: 'signinapp-d30aa',
    authDomain: 'signinapp-d30aa.firebaseapp.com',
    storageBucket: 'signinapp-d30aa.appspot.com',
    measurementId: 'G-M33JSFT2NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55Eis2f6cMpnY0KHvEovKWKXJcc79rzs',
    appId: '1:447433637466:android:9b8d2c02974c3529ba6263',
    messagingSenderId: '447433637466',
    projectId: 'signinapp-d30aa',
    storageBucket: 'signinapp-d30aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJlojVlTqFsclc9pQw-WQ-MT3xnuZHT4',
    appId: '1:447433637466:ios:166101eb96c06e2cba6263',
    messagingSenderId: '447433637466',
    projectId: 'signinapp-d30aa',
    storageBucket: 'signinapp-d30aa.appspot.com',
    iosClientId: '447433637466-qm9q7plpk9ljjsmq33rqifnskr9lnqjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjJlojVlTqFsclc9pQw-WQ-MT3xnuZHT4',
    appId: '1:447433637466:ios:8cf47b84f445dafbba6263',
    messagingSenderId: '447433637466',
    projectId: 'signinapp-d30aa',
    storageBucket: 'signinapp-d30aa.appspot.com',
    iosClientId: '447433637466-edjp6ifukeoae43t3sgnl91qp6mqven9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
